# Nic neupravuj, pokud nevíš, co děláš.
# Všechno, co bys mohl chtít upravit, by mělo jít spravovat pomocí příkazu "/inventory"

arena-fill:
  '1':
    block: air
    pos1: 31 -64 24
    pos2: -31 99 -24
  
  # Red spawn platform
  '2':
    block: bedrock
    pos1: -28 -1 2
    pos2: -24 -64 -2
  '3':
    block: red_wool
    pos1: -28 -1 2
    pos2: -24 -1 -2
  '4':
    block: bedrock
    pos1: -27 -1 1
    pos2: -25 -1 -1
  
  # Yellow spawn platform
  '5':
    block: bedrock
    pos1: 28 -1 2
    pos2: 24 -64 -2
  '6':
    block: yellow_wool
    pos1: 28 -1 2
    pos2: 24 -1 -2
  '7':
    block: bedrock
    pos1: 27 -1 1
    pos2: 25 -1 -1

inventory:
  default:
    axe: 0
    planks1: 1
    pickaxe: 2
    bow: 3
    k1: 4
    pork: 5
    gapple: 6
    pearl: 7
    water: 8
    
    sword: 27
    flint: 18
    arrow: 9
    potato: 14
    bucket: 19
    
    stone1: 15
    stone2: 24
    stone3: 33
    planks2: 17
    planks3: 26
    planks4: 35
    logs1: 16
    logs2: 25
    logs3: 34
    
    k2: 10
    k3: 11
    k4: 12
    k5: 13
    k6: 20
    k7: 21
    k8: 22
    k9: 23
    k10: 28
    k11: 29
    k12: 30
    k13: 31
    k14: 32
    
    feet: 36
    legs: 37
    chest: 38
    head: 39
    
    shield: 40    

saved-inventories:
